namespace UAS.Payroll;

using Microsoft.HumanResources.Setup;

// DEPENDENCIA: Este permission set cubre únicamente los objetos del módulo Payroll (rango 50000-61000).
// Para acceso completo se requieren además los siguientes roles estándar de BC:
//   • Employee / HR Setup  → "D365 HUMAN RES, FULL" o equivalente
//   • Job (Marea)          → "D365 PROJECT MGMT" o equivalente
// Asignar junto a uno de los roles anteriores.
permissionset 50302 "Liq. Pesca - Lectura"
{
    // Read-only access to all payroll data and reports.
    Assignable = true;
    Caption = 'Liq. Pesca - Lectura';

    Permissions =
        // ── Tables — read only ──
        tabledata "Estado Empleado" = R,
        tabledata "Tipo Liquidación" = R,
        tabledata "Cód. Estado Empleado" = R,
        tabledata "Convenio Colectivo" = R,
        tabledata "Categoría CCT" = R,
        tabledata "Concepto Liquidación" = R,
        tabledata "Parámetro Vigente" = R,
        tabledata "Personal Proyecto" = R,
        tabledata "Período Liquidación" = R,
        tabledata "Liquidación" = R,
        tabledata "Línea Liquidación" = R,
        tabledata "Tabla Escalonada" = R,
        tabledata "Tabla Escalonada Det." = R,
        tabledata "Fuente Datos Liquidación" = R,
        tabledata "Parámetro" = R,
        tabledata "Fracción Acumulador" = R,
        tabledata "Variable Sistema Liq." = R,
        tabledata "Concepto CCT Vigente" = R,
        tabledata "Incidencia Liquidación" = R,
        tabledata "Novedad Liquidación" = R,
        tabledata "Árbol Liquidaciones Buffer" = R,
        tabledata "Clase Entidad Liq." = R,
        tabledata "Entidad Liq." = R,
        tabledata "Tipo Atributo Liq." = R,
        tabledata "Valor Atributo Liq." = R,
        tabledata "Atributo Entidad Liq." = R,
        tabledata "Registro Proceso Liq." = R,
        tabledata "Historial Fórmula Concepto" = R,
        tabledata "Entrada Registro Liq." = R,
        tabledata "Ded. Ganancias Vigente" = R,
        tabledata "Ded. Ganancias Empleado" = R,
        tabledata "Detalle Variable Línea Liq." = R,
        tabledata "Resumen Variable Liq." = R,
        tabledata "Detalle Acumulador Liq." = R,
        tabledata "Uso Parámetro Liq." = R,
        tabledata "Control Marea Buffer" = RIMD,
        tabledata "Francos Buffer Liq." = RIMD,
        tabledata "Saldo Inicial Francos Liq." = R,
        tabledata "Cobertura Liq. Buffer" = RIMD,
        // RIMD aun en el rol de solo lectura, y no es una excepción: son tablas temporales. La vista
        // se construye escribiendo en memoria, así que sin permiso de escritura el usuario de lectura
        // no puede ni abrirlas. Nada de esto llega a la base.
        tabledata "Fase Alta Empleado" = RIMD,
        tabledata "Antigüedad Plantilla Buffer" = RIMD,
        // ── Sincronización con NAV 2013R2 ──
        tabledata "Ctrl Sinc NAV" = R,
        tabledata "Config Sinc NAV" = R,
        tabledata "Stg Dia Abordo Cab NAV" = R,
        tabledata "Stg Dia Abordo Lin NAV" = R,
        tabledata "Stg Informe Cap Cab NAV" = R,
        tabledata "Stg Informe Cap Lin NAV" = R,
        tabledata "Stg Proyecto NAV" = R,
        tabledata "Stg Empleado NAV" = R,
        tabledata "Stg Descarga Cab NAV" = R,
        tabledata "Stg Descarga Lin NAV" = R,
        tabledata "Human Resources Setup" = R,
        // ── Tables — schema ──
        table "Estado Empleado" = X,
        table "Cód. Estado Empleado" = X,
        table "Convenio Colectivo" = X,
        table "Categoría CCT" = X,
        table "Concepto Liquidación" = X,
        table "Parámetro Vigente" = X,
        table "Personal Proyecto" = X,
        table "Período Liquidación" = X,
        table "Liquidación" = X,
        table "Línea Liquidación" = X,
        table "Tabla Escalonada" = X,
        table "Tabla Escalonada Det." = X,
        table "Fuente Datos Liquidación" = X,
        table "Parámetro" = X,
        table "Fracción Acumulador" = X,
        table "Variable Sistema Liq." = X,
        table "Concepto CCT Vigente" = X,
        table "Incidencia Liquidación" = X,
        table "Novedad Liquidación" = X,
        table "Árbol Liquidaciones Buffer" = X,
        table "Clase Entidad Liq." = X,
        table "Entidad Liq." = X,
        table "Tipo Atributo Liq." = X,
        table "Valor Atributo Liq." = X,
        table "Atributo Entidad Liq." = X,
        table "Registro Proceso Liq." = X,
        table "Historial Fórmula Concepto" = X,
        // Único codeunit de este conjunto: sólo lee, y sin él las listas de novedades e incidencias
        // no pueden resolver el nombre del concepto.
        codeunit "Descripción Concepto Liq." = X,
        table "Entrada Registro Liq." = X,
        table "Ded. Ganancias Vigente" = X,
        table "Ded. Ganancias Empleado" = X,
        table "Detalle Variable Línea Liq." = X,
        table "Resumen Variable Liq." = X,
        table "Detalle Acumulador Liq." = X,
        table "Uso Parámetro Liq." = X,
        table "Control Marea Buffer" = X,
        table "Francos Buffer Liq." = X,
        table "Saldo Inicial Francos Liq." = X,
        table "Cobertura Liq. Buffer" = X,
        table "Ctrl Sinc NAV" = X,
        table "Config Sinc NAV" = X,
        table "Stg Dia Abordo Cab NAV" = X,
        table "Stg Dia Abordo Lin NAV" = X,
        table "Stg Informe Cap Cab NAV" = X,
        table "Stg Informe Cap Lin NAV" = X,
        table "Stg Proyecto NAV" = X,
        table "Stg Empleado NAV" = X,
        table "Stg Descarga Cab NAV" = X,
        table "Stg Descarga Lin NAV" = X,
        // ── Pages ──
        page "Lista Liquidaciones" = X,
        page "Ficha Liquidación" = X,
        page "Líneas Liquidación" = X,
        page "Estados Empleado" = X,
        page "Cód. Estados Empleado" = X,
        page "Buques" = X,
        page "Tipos Liquidación" = X,
        page "Estados de Buque" = X,
        page "Estado Empleado FactBox" = X,
        page "Convenios Colectivos" = X,
        page "Categorías CCT" = X,
        page "Conceptos Liquidación" = X,
        page "Concepto Liq. Card" = X,
        page "Parámetros" = X,
        page "Parámetro Card" = X,
        page "Parámetro Vigente Subpag" = X,
        page "Parámetro Sufijo Sub" = X,
        page "Parámetros Vigentes" = X,
        page "Personal Proyecto" = X,
        page "Períodos Liquidación" = X,
        page "Tabla Escalonada List" = X,
        page "Tabla Escalonada Card" = X,
        page "Tabla Escalonada Det. Sub" = X,
        page "Fuente Datos Liquidación" = X,
        page "Fuente Datos Card" = X,
        page "Fracción Acumulador Sub" = X,
        page "Variable Sistema Liq." = X,
        page "Concepto CCT Sub" = X,
        page "Incidencias Liquidación Sub" = X,
        page "Novedades Liquidación" = X,
        page "Registros Proceso Liq." = X,
        page "Historial Fórmulas Concepto" = X,
        page "Ficha Cambio Fórmula" = X,
        page "Clases de Entidad" = X,
        page "Entidades" = X,
        page "Ficha Entidad" = X,
        page "Tipos de Atributo" = X,
        page "Ficha Tipo Atributo" = X,
        page "Valores Atributo Sub" = X,
        page "Valores de Atributo" = X,
        page "Atributos de Entidad" = X,
        page "Atributos Entidad Sub" = X,
        page "Estados Empleado Sub" = X,
        page "Fases Alta Empleado Sub" = X,
        page "Fases de Alta" = X,
        page "Antigüedad de la Plantilla" = X,
        page "Árbol de Liquidaciones" = X,
        page "Árbol de Parámetros" = X,
        page "Claves de Parámetro a Revisar" = X,
        page "Fórmulas con Errores" = X,
        page "Ficha Valor Parámetro" = X,
        page "Atributos Entidad FactBox" = X,
        page "Ficha Registro Proceso Liq." = X,
        page "Entradas Registro Liq." = X,
        page "Entradas Registro Liq. Sub" = X,
        page "Detalle Variable Línea Sub" = X,
        page "Variables Cálculo Línea" = X,
        page "Ded. Ganancias Vigente" = X,
        page "Ded. Ganancias Vigente Card" = X,
        page "Ded. Ganancias Empleado Sub" = X,
        page "Payroll Role Center" = X,
        page "Detalle Acumulador Liq." = X,
        page "Control Liquidación Marea" = X,
        page "Control Marea Matriz Sub" = X,
        page "Francos por Tripulante" = X,
        page "Saldo Inicial de Francos" = X,
        page "Control de Cobertura Liq." = X,
        page "Novedades Liq. Sub" = X,
        page "Control Marea Difs. Sub" = X,
        page "Marea Variables Comunes Sub" = X,
        page "Acumuladores Liq. Sub" = X,
        page "Control Sinc. NAV" = X,
        page "Config Sinc NAV" = X,
        page "Sinc. Proyectos NAV" = X,
        page "Sinc. Empleados NAV" = X,
        page "Sinc. Cab. Descargas NAV" = X,
        page "Sinc. Lín. Descargas NAV" = X,
        // ── Reports ──
        report "Recibo de Sueldo" = X;
}
